modLoader="javafml" #mandatory
loaderVersion="${fgrange}"
license="${modlicense}"
issueTrackerURL="https://github.com/${github_project}/issues"
displayTest="IGNORE_SERVER_VERSION"

[[mods]]
    modId="${modid}"
    version="${modversion}"
    displayName="${modname}"
    displayTest="IGNORE_SERVER_VERSION"
    logoFile="pack.png" #optional
    authors="${modauthor}" #optional
    credits="${modcredits}"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/embeddiumplus"
    description='''${mod_description}'''

[[dependencies.${modid}]]
    modId="forge"
    mandatory=true
    versionRange="${fgrange}"
    ordering="NONE"
    side="CLIENT"

[[dependencies.${modid}]]
    modId="minecraft"
    mandatory=true
    versionRange="${mcrange}"
    ordering="NONE"
    side="CLIENT"

[[dependencies.${modid}]]
    modId="embeddium"
    mandatory=true
    versionRange="${embeddiumrange}"
    ordering="AFTER"
    side="CLIENT"

[[dependencies.${modid}]]
    modId="zume"
    mandatory=false
    versionRange="${zumerange}"
    ordering="AFTER"
    side="CLIENT"

[[dependencies.${modid}]]
    modId="textrues_embeddium_options"
    mandatory=true
    versionRange="*"
    ordering="AFTER"
    side="CLIENT"